# Problem 2
# =========


#    Each new term in the Fibonacci sequence is generated by adding the
#    previous two terms. By starting with 1 and 2, the first 10 terms will be:

#                      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#    By considering the terms in the Fibonacci sequence whose values do not
#    exceed four million, find the sum of the even-valued terms.

   
#    Answer: 4194eb91842c8e7e6df099ca73c38f28

#Fibonacci
def F():
    a, b = 1 , 2
    while b < 4000000:
        if b % 2 == 0:
    		yield b
        a, b = b, a + b


test = F()
print sum(test)


# a, b, even_sum = 1, 2, 0
#     while b < 4000000:
#     	if b % 2 == 0:
#     		even_sum += b
#     a, b = b, a + b
# print even_sum	